AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 15
    MemorySize: 256
    Runtime: nodejs18.x

Parameters:
  OPENAI_API_KEY:
    Type: String
    NoEcho: true
    Description: OpenAI API Key
  TwilioAccountSid:
    Type: String
    NoEcho: true
    Description: Twilio Account SID
  TwilioAuthToken:
    Type: String
    NoEcho: true
    Description: Twilio Auth Token
  TwilioPhoneNumber:
    Type: String
    Description: Twilio Phone Number
  ManagerPhoneNumber:
    Type: String
    Description: Manager's Phone Number for Escalations

Resources:
  # Application IAM Roles
  ApplicationRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${AWS::StackName}-application-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 
                - lambda.amazonaws.com
                - sagemaker.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      Policies:
        - PolicyName: ApplicationAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sagemaker:InvokeEndpoint
                  - sagemaker:CreateEndpoint
                  - sagemaker:CreateEndpointConfig
                  - sagemaker:CreateModel
                Resource: '*'
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${AWS::StackName}-*

  MessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/message/
      Handler: index.handler
      Role: !GetAtt ApplicationRole.Arn
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OPENAI_API_KEY
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          TWILIO_PHONE_NUMBER: !Ref TwilioPhoneNumber
          SAGEMAKER_ENDPOINT_NAME: !Ref MessageClassifierEndpoint
      Events:
        MessageEvent:
          Type: Api
          Properties:
            Path: /message
            Method: post

  EscalateFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/functions/escalate/
      Handler: index.handler
      Role: !GetAtt ApplicationRole.Arn
      Environment:
        Variables:
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          TWILIO_PHONE_NUMBER: !Ref TwilioPhoneNumber
          MANAGER_PHONE_NUMBER: !Ref ManagerPhoneNumber
      Events:
        EscalateEvent:
          Type: Api
          Properties:
            Path: /escalate
            Method: post

Outputs:
  ApplicationRoleArn:
    Description: "ARN of the application IAM role"
    Value: !GetAtt ApplicationRole.Arn
  MessageClassifierEndpoint:
    Description: "SageMaker Endpoint for Message Classification"
    Value: !GetAtt MessageClassifierEndpoint.EndpointName
  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"